site_name: Guide to x86-32 Kernel Development
theme:
  name: 'material'
pages:
- Introduction: 'index.md'
- Preparation: 
  - 'Preparation': 'Preparation/Preparation.md'
  - 'Boot Sequence': 'Preparation/Boot Sequence.md'
  - 'UEFI': 'Preparation/UEFI.md'
markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
  - toc:
      permalink: true
